have user define their own repo for custom production images

diff --git a/.github/workflows/build_test_docs.yml b/.github/workflows/build_test_docs.yml
--- a/.github/workflows/build_test_docs.yml
+++ b/.github/workflows/build_test_docs.yml
@@ -134,7 +134,7 @@ jobs:
       name: Determine Image Tags
       id: generate_tag
       run: |
-        _repo="ldmx/pro"
+        _repo=$(cat .github/workflows/production_image_repo)
         _tag=""
         if [[ $GITHUB_REF == refs/tags/* ]]; then
           # if pushing a git tag ==> get the git tag for the docker tag
@@ -146,6 +146,9 @@ jobs:
           _tag=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
           if [ "${{ github.event.repository.default_branch }}" = "$_tag" ]; then
             _tag=edge
+          elif [ "$_repo" = "ldmx/pro" ]; then
+            echo "Can't push a non-master branch commit to 'ldmx/pro'. Create your own repository."
+            exit 2
           fi
         else
           echo "Running Determine Image Tags on a commit that isn't a tag or a branch."
